# `docker compose up -d`
# `docker compose down`

services:
  rabbitmq-server:
    image: rabbitmq:3-management
    container_name: rabbitmq-server
    restart: always
    hostname: docker-rabbitmq
    ports:
      - "5673:5672"
      - "15673:15672"
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq/mnesia
    environment:
      TZ: Asia/Shanghai
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: qwe@123
    networks:
      - rabbitmq-network

  rabbitmq-producer:
    image: amazoncorretto:21-alpine
    container_name: rabbitmq-producer
    restart: always
    working_dir: /opt
    ports:
      - "8080:8080"
    volumes:
      - ./rabbitmq-producer/build/libs/rabbitmq-producer-0.0.1-SNAPSHOT.jar:/opt/app.jar
      - ./rabbitmq-producer/build/config:/opt/config
    environment:
      TZ: Asia/Shanghai
      SPRING_RABBITMQ_HOST: rabbitmq-server
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: admin
      SPRING_RABBITMQ_PASSWORD: qwe@123
    # 等待 30 秒后启动，确保 RabbitMQ 服务已经启动
    command: sh -c "sleep 30s && java -jar app.jar"
    depends_on:
      - rabbitmq-server
    networks:
      - rabbitmq-network

  rabbitmq-consumer:
    image: amazoncorretto:21-alpine
    container_name: rabbitmq-consumer
    restart: always
    working_dir: /opt
    ports:
      - "8081:8081"
    volumes:
      - ./rabbitmq-consumer/build/libs/rabbitmq-consumer-0.0.1-SNAPSHOT.jar:/opt/app.jar
      - ./rabbitmq-consumer/build/config:/opt/config
    environment:
      TZ: Asia/Shanghai
      SPRING_RABBITMQ_HOST: rabbitmq-server
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: admin
      SPRING_RABBITMQ_PASSWORD: qwe@123
    # 等待 30 秒后启动，确保 RabbitMQ 服务已经启动
    command: sh -c "sleep 30s && java -jar app.jar"
    depends_on:
      - rabbitmq-server
    networks:
      - rabbitmq-network

networks:
  rabbitmq-network:
    driver: bridge
