# `docker compose up -d`
# `docker compose down`

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    hostname: docker-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq-config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbitmq-config/definitions.json:/etc/rabbitmq/definitions.json
      - ./rabbitmq-data:/var/lib/rabbitmq/mnesia
    environment:
      TZ: Asia/Shanghai
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: qwe@123
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - rabbitmq-network

  rabbitmq-producer:
    depends_on:
      rabbitmq:
        condition: service_healthy
    image: amazoncorretto:21-alpine
    container_name: rabbitmq-producer
    restart: always
    working_dir: /opt
    ports:
      - "8080:8080"
    volumes:
      - ./rabbitmq-producer/build/libs/rabbitmq-producer-0.0.1-SNAPSHOT.jar:/opt/app.jar
      - ./rabbitmq-producer/build/config:/opt/config
    environment:
      TZ: Asia/Shanghai
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: admin
      SPRING_RABBITMQ_PASSWORD: qwe@123
    command: ["java", "-jar", "app.jar"]
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 3s
      retries: 3
    networks:
      - rabbitmq-network

  rabbitmq-consumer:
    depends_on:
      rabbitmq:
        condition: service_healthy
    image: amazoncorretto:21-alpine
    container_name: rabbitmq-consumer
    restart: always
    working_dir: /opt
    ports:
      - "8081:8081"
    volumes:
      - ./rabbitmq-consumer/build/libs/rabbitmq-consumer-0.0.1-SNAPSHOT.jar:/opt/app.jar
      - ./rabbitmq-consumer/build/config:/opt/config
    environment:
      TZ: Asia/Shanghai
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: admin
      SPRING_RABBITMQ_PASSWORD: qwe@123
    command: ["java", "-jar", "app.jar"]
    networks:
      - rabbitmq-network

networks:
  rabbitmq-network:
    driver: bridge
