eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8765
spring:
  application:
    name: api-gateway
management:
  endpoints:
    web:
      base-path: /gateway/actuator
      exposure:
        include: health,info,metrics
