eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8765
spring:
  application:
    name: api-gateway
management:
  endpoints:
    web:
      base-path: /gateway/actuator
      exposure:
        include: health,info,metrics

  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
logging:
  pattern:
    correlation: "[%X{traceId:-},%X{spanId:-}]"
