server:
  port: 8081
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: qwe@123
    listener:
      simple:
        acknowledge-mode: manual
web-kit:
  security:
    permit-all-paths: /api/v1/**