spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: file:///Users/wxj/Codes/miroservices-git-local-config-repo
server:
  port: 8888