eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
#server:
#  port: 8000
spring:
  application:
    name: currency-exchange-service
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:mysql://localhost:3306/test_del?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: qwe@123
resilience4j:
  retry:
    instances:
      getRealtimeExchangeRates:
        max-attempts: 5
        wait-duration: 1s
        enable-exponential-backoff: true
  circuitbreaker:
    instances:
      getRealtimeExchangeRates:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        record-exceptions:
          - org.springframework.web.client.ResourceAccessException
  ratelimiter:
    instances:
      getRealtimeExchangeRates:
        limit-for-period: 2
        limit-refresh-period: 10s
        timeout-duration: 1s
  bulkhead:
    instances:
      getRealtimeExchangeRates:
        max-concurrent-calls: 1
mybatis:
  mapper-locations: classpath:mapper/*.xml

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
