eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8000
spring:
  application:
    name: currency-exchange-service
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:mysql://localhost:3306/test_del?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: qwe@123
resilience4j:
  retry:
    instances:
      realtimeExchangeRatesService:
        max-attempts: 5
        wait-duration: 1s
        enable-exponential-backoff: true
  circuitbreaker:
    instances:
      realtimeExchangeRatesService:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        record-exceptions:
          - org.springframework.web.client.ResourceAccessException
mybatis:
  mapper-locations: classpath:mapper/*.xml
