eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8000
spring:
  application:
    name: currency-exchange-service
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:mysql://localhost:3306/test_del?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: qwe@123
resilience4j:
  retry: # 重试
    instances:
      paymentService: # 重试实例名称
        max-attempts: 5 # 最大尝试次数
        wait-duration: 1s # 重试间隔
        enable-exponential-backoff: true # 是否启用指数退避
  circuitbreaker: # 断路器
    instances:
      paymentService: # 断路器实例名称
        failure-rate-threshold: 50 # 失败率阈值
        wait-duration-in-open-state: 10s # 开启状态持续时间
        permitted-number-of-calls-in-half-open-state: 3 # 半开状态下允许的调用次数
mybatis:
  mapper-locations: classpath:mapper/*.xml
