DROP TABLE IF EXISTS `mybatis`;
CREATE TABLE `mybatis` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(255)  DEFAULT NULL,
  `date` DATETIME DEFAULT NULL,
  `local_date_time` DATETIME DEFAULT NULL,
  `local_date` DATE DEFAULT NULL
) ENGINE = InnoDB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
